# View a detector shape in the OpenGL viewer WITHOUT /run/reinitializeGeometry
# (rebuilding geometry after init crashes this app -- same bug view_shape.sh
# dodged on macOS). Works by setting the shape BEFORE /run/initialize: the app
# reads init_vis.mac from the current directory, so we launch from a scratch
# dir containing a doctored copy. No rebuild needed; safe to use while sweeps
# are running in build\.
#
# Usage:
#   .\view_shape.ps1 h13                       # named shape (S, pP, h01..h35, ...)
#   .\view_shape.ps1 "0,0;1,0;2,0;0,1;1,1;2,1" # arbitrary cells (col,row;...)
#   .\view_shape.ps1 h13 -Padding 2.0          # padding in mm (default 1.0)
param(
    [string]$Shape = "S",
    [double]$Padding = 1.0
)
$root = $PSScriptRoot

# Self-contained Geant4 environment -- works even in terminals opened before
# the user-level env vars were set (those sessions miss the DLL path and the
# exe dies instantly with no output).
$g4 = 'C:\Geant4\geant4-11.4.1-win64'
$g4data = "$g4\share\Geant4\data"
if ($env:Path -notlike "*$g4\bin*") { $env:Path += ";$g4\bin" }
$env:G4NEUTRONHPDATA = "$g4data\G4NDL4.7.1"
$env:G4LEDATA = "$g4data\G4EMLOW8.8"
$env:G4LEVELGAMMADATA = "$g4data\PhotonEvaporation6.1.2"
$env:G4RADIOACTIVEDATA = "$g4data\RadioactiveDecay6.1.2"
$env:G4PARTICLEXSDATA = "$g4data\G4PARTICLEXS4.2"
$env:G4SAIDXSDATA = "$g4data\G4SAIDDATA2.0"
$env:G4ENSDFSTATEDATA = "$g4data\G4ENSDFSTATE3.0"
$viewDir = Join-Path $root "view"
New-Item -ItemType Directory -Force $viewDir | Out-Null

$detCmd = if ($Shape -match ",") { "/det/cells $Shape" } else { "/det/shape $Shape" }

@"
# auto-generated by view_shape.ps1 -- shape is set BEFORE /run/initialize
/control/verbose 2
/control/saveHistory
/run/verbose 2
$detCmd
/det/padding $Padding mm
/run/initialize
/control/execute vis.mac
"@ | Out-File (Join-Path $viewDir "init_vis.mac") -Encoding ascii

Copy-Item (Join-Path $root "vis.mac") $viewDir -Force

Write-Host "Viewing: $detCmd  (padding $Padding mm). Close the viewer / type exit to quit."
Push-Location $viewDir
try { & (Join-Path $root "build\exampleB1.exe") }
finally {
    Pop-Location
    if ($LASTEXITCODE -ne 0) {
        Write-Host "exampleB1.exe exited with code $LASTEXITCODE" -ForegroundColor Red
        if ($LASTEXITCODE -eq -1073741515) {
            Write-Host "(0xC0000135: a required DLL was not found -- check $g4\bin exists)" -ForegroundColor Red
        }
    }
}
